name: cooltools pileup
description: Pileup features for a resolution in an .mcool file
url: https://github.com/open2c/cooltools
authors:
  - Ilya Flyamer
input:
  - a multiresolution cooler file (.mcool)
  - a file with features to pileup
  - (optional) file with expected
output:
  - >
    A file (.npz or .h5) with piled up snippets.
    Has to have a {resolution} wildcard that specifies the resolution for the analysis.
params:
  view: > 
    Path to a bed-style file with region coordinates and names to use for analysis
  extra: Any additional arguments to pass
notes:
