name: cooltools eigs_cis
description: Calculate cis eigenvectors for a resolution in an .mcool file
url: https://github.com/open2c/cooltools
authors:
  - Ilya Flyamer
input:
  - a multiresolution cooler file (.mcool)
  - (optional) phasing track file
output:
  - >
    A .tsv file with values of cis eigenvectors at each bin.
    Another file with eigenvalues is saved into {output}.lam.txt.
    Can have a {resolution} wildcard that specifies the resolution for the analysis,
    then it doesn't need to be specified as a parameter.
params:
  view: > 
    Path to a bed-style file with region coordinates and names to use for analysis
  resolution: >
    Optional, can be instead specified as a wildcard in the output
  extra: Any additional arguments to pass
notes:
