name: cooltools eigs_trans
description: Calculate trans eigenvectors for a resolution in an .mcool file
url: https://github.com/open2c/cooltools
authors:
  - Ilya Flyamer
input:
  - a multiresolution cooler file (.mcool)
  - (optional) phasing track file
output:
  - >
    A .tsv file with values of trans eigenvectors at each bin.
    Another file with eigenvalues is saved into {output}.lam.txt.
    Has to have a {resolution} wildcard that specifies the resolution for the analysis.
params:
  view: > 
    Path to a bed-style file with region coordinates and names to use for analysis
  extra: Any additional arguments to pass
notes:
